name: Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          theme: dark-dimmed
          config_timezone: Africa/Casablanca
